// ui/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ShoppingCartApiService } from './services/shopping-cart-api.service';
import { StorageService } from './services/storage.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private shoppingCartApiService : ShoppingCartApiService,
              private storageService : StorageService){};

  ngOnInit(){
    document.title = "Shopping Cart";
    this.assignItems();
    this.assignCart();
  }

  items : any[] = [];
  shoppingCart : any = this.storageService.getCurrentCart();

  assignItems() : void {
    this.shoppingCartApiService.getData("items").subscribe({
      next : data => {
        this.items = data.items;
      },
      error : response => {
        alert(response.error.message || response.error);
      }
    });
  }

  assignCart() : void {
    if(!this.shoppingCart){
      //create new cart using the api, then store it in sessionStorage
      this.shoppingCartApiService.postData("shopping-carts", {}).subscribe({
        next : data => {
          this.shoppingCart = data.shoppingCart;
          this.storageService.setCurrentCart(this.shoppingCart);
        },
        error : response => {
          alert(response.error.message || response.error);
        }
      });
    }
  }
}

<app-header [shoppingCart]="shoppingCart"></app-header>
<div class="col-12 card-deck item-cards">
  <div class="card" *ngFor="let i of items">
    <app-item-card [item]="i"></app-item-card>
  </div>
</div>
<app-footer></app-footer>

// react-ui/src/App.js
import React from 'react';
import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import ItemCard from './components/item-card/Item-Card';
import ShoppingCartService from './services/shopping-cart-service';
import logo from './logo.svg';
import './App.css';
const shoppingCartService = new ShoppingCartService();

class App extends React.Component {
  constructor(props){
    super(props);
    this.state = {
      shoppingCart : null,
      items : null
    }
  };

  assignCart(){
    //create new cart using the api, then store it in sessionStorage
    if(!this.state.shoppingCart){
      shoppingCartService.postData("shopping-carts", {})
        .then((response => {
          this.setState({
            shoppingCart : response.data.shoppingCart
          });
        }))
        .catch((err) => {
          console.log(err);
        })
    }
  }

  assignItems(){
    if(!this.state.items){
      shoppingCartService.getData("items")
        .then((response => {
          this.setState({
            items : response.data.items
          });
        }))
        .catch((err) => {
          console.log(err);
        })
    }
  }

  //Create a list of item-cards given the current items in the cart
  generateItemCards(){
    let itemCards = [];
    if(this.state.items){
      for(let item of this.state.items){
        itemCards.push(
          <ItemCard item = {item}></ItemCard>
        );
      }
    }
    return itemCards;
  }

	render() {
    console.log(shoppingCartService);
    this.assignCart();
    this.assignItems();
		return (
			<div className="app-body">
        <Header shoppingCart = {this.state.shoppingCart} ></Header>
        <div class="col-12 card-deck item-cards">
          {this.generateItemCards()}
        </div>
				<Footer></Footer>
			</div>
		);
	};
}

export default App;
