// react-ui/src/components/header/Header.js
import React from 'react';
import './Header.css';

class Header extends React.Component {
  render(){
    let cartIcon;
    //check if a shoppingCart object was fetched from the api
    if(this.props.shoppingCart){
      cartIcon =  (
        <h5 className="cart-icon">
          <i className="fas fa-shopping-cart cart-icon"></i>
          <span className="badge badge-pill badge-warning cart-badge">
            {this.props.shoppingCart.items.length}
          </span>
        </h5>
      );
    }

    return (
      <div className="col-12 header">
        <h2 className="header">Shopping Cart</h2>
        {cartIcon}
      </div>
    );
  }
};

export default Header;

// ui/src/app/components/header/header.component.ts
import { Component, OnInit, Input} from '@angular/core';
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';
import { StorageService } from '../../services/storage.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  constructor(private modalService : NgbModal,
              private storageService : StorageService) { }

  ngOnInit() {
    if(!this.shoppingCart){
      this.shoppingCart = this.storageService.getCurrentCart();
    }
  }

  @Input() shoppingCart : any = this.storageService.getCurrentCart();

  open(content){
    this.modalService.open(content);
  }
}

<div class="col-12 header">
  <h2 class="header">Shopping Cart</h2>
  <h5 class="cart-icon" (click)="open(cart)" *ngIf="shoppingCart">
    <i class="fas fa-shopping-cart cart-icon"></i>
    <span class="badge badge-pill badge-warning cart-badge">{{shoppingCart.items.length || 0}}</span>
  </h5>
</div>

<ng-template #cart let-modal>
  <app-cart-modal></app-cart-modal>
</ng-template>
