// ui/src/app/components/item-card/item-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';
import { StorageService } from '../../services/storage.service';

@Component({
  selector: 'app-item-card',
  templateUrl: './item-card.component.html',
  styleUrls: ['./item-card.component.css']
})
export class ItemCardComponent implements OnInit {
  constructor(private modalService : NgbModal,
              private storageService : StorageService) { }

  ngOnInit() {
  }

  @Input() item : any = {
    "id" : null,
    "description" : null,
    "unit_price" : null,
    "volume_discounts" : []
  }
  shoppingCart : any = this.storageService.getCurrentCart();

  open(content){
    this.modalService.open(content, {"size": "sm"});
  }
}

<div class="card-header" *ngIf="item.description">
  <h4 class="item-description">{{item.description}}</h4>
</div>
<div class="card-body">
  <div *ngIf="item.unit_price">
    <b class="d-inline">1 </b>
    <p class="d-inline">for </p>
    <b class="d-inline">{{item.unit_price | currency: 'USD'}}</b>
  </div>
  <div *ngFor="let d of item.volume_discounts">
    <b class="d-inline">{{d.number}} </b>
    <p class="d-inline">for </p>
    <b class="d-inline">{{d.price | currency: 'USD'}}</b>
  </div>
</div>
<button class="btn btn-primary btn-md item-btn" (click)="open(addItem)">Add Item</button>

<ng-template #addItem let-modal>
  <app-item-modal [item]="item"></app-item-modal>
</ng-template>

// react-ui/src/components/item-card/Item-Card.js
import React from 'react';
import './Item-Card.css';
import Currency from 'react-currency-formatter';

export default function ItemCard(props){
  //initialize placeholder values for conditional ui elements
  let cardHeader, unitPrice;

  //triggers upon clickint the add item button, set the selected item & open item-modal
  const handleClick = function(){
    props.setSelectedItem(props.item);
    props.toggleItemModal(!props.showItemModal);
  }

  //generate conditional ui elements as needed
  if(props.item && props.item.description){
    cardHeader = (
      <div className="card-header">
        <h4 className="item-description">{props.item.description}</h4>
      </div>
    );
  }
  if(props.item && props.item.unit_price){
    unitPrice = (
      <div>
        <b className="d-inline">1 </b>
        <p className="d-inline">for </p>
        <b className="d-inline">
          <Currency quantity={props.item.unit_price} currency="USD"/>
        </b>
      </div>
    );
  }

  return (
    <div className="card">
      {cardHeader}
      <div className="card-body">
        {unitPrice}
        {props.item.volume_discounts.map((volumeDiscount) => {
          return (
            <div>
              <b className="d-inline">{volumeDiscount.number} </b>
              <p className="d-inline">for </p>
              <b className="d-inline">
                <Currency quantity={volumeDiscount.price} currency="USD"/>
              </b>
            </div>
          )
        })}
      </div>
      <button className="btn btn-primary btn-md item-btn" onClick={handleClick}>
        Add Item
      </button>
    </div>
  );
}
